<?php
/**
 * UserCityRepository
 *
 * @category   PHP5
 * @package    Entity
 * @subpackage Repository
 * @author     Tairik Jean da Costa <tairikme@hotmail.com>
 * @license    http://www.tairik.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/simplerest.git
 */
namespace Acme\DemoBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;
/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category   PHP5
 * @package    Entity
 * @subpackage Repository
 * @author     Tairik Jean da Costa <tairikme@hotmail.com>
 * @license    http://www.tairik.ca/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/simplerest.git
 */

class UserCityRepository extends EntityRepository
{

}