<?php
/**
 * UserCity
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */
namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */

class UserPhoto
{

    /**
     * @var integer
     */
    private $id;

    /**
     * @var integer
     */
    private $userId;

    /**
     * @var string
     */
    private $photo;

    /**
     * @var interger
     */
    private $public;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set userId
     *
     * @param integer $userId
     * @return UserCity
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * Get userId
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Set photo
     *
     * @param string $photo
     * @return UserPhoto
     */
    public function setPhoto($photo)
    {
        $this->photo = $photo;

        return $this;
    }

    /**
     * Get photo
     *
     * @return integer
     */
    public function getPhoto()
    {
        return $this->photo;
    }

    /**
     * Set public
     *
     * @param string $public
     * @return UserPhoto
     */
    public function setPublic($public)
    {
        $this->public = $public;

        return $this;
    }

    /**
     * Get public
     *
     * @return integer
     */
    public function getPublic()
    {
        return $this->public;
    }
}