<?php
/**
 * User
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */
namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */

class User
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $firstName;

    /**
     * @var string
     */
    private $lastName;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstName
     *
     * @param string $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Get firstName
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }

    /**
     * Set lastName
     *
     * @param string $lastName
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Get lastName
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }
}
