<?php
/**
 * UserCity
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */
namespace Acme\DemoBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @category   PHP5
 * @package    AcmeBundle
 * @subpackage Entity
 * @author     Tairik Jean da Costa <tairik.dacosta@egocentrix.com>
 * @license    http://www.egocentrix.com/license/ BSD Licence
 * @link       https://tairik@bitbucket.org/tairik/new-cloudadmin.git
 */

class UserCity
{

    /**
     * @var integer
     */
    private $id;

    /**
     * @var integer
     */
    private $userId;

    /**
     * @var integer
     */
    private $cityId;



    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->userId;
    }

    /**
     * Set userId
     *
     * @param integer $userId
     * @return UserCity
     */
    public function setUserId($userId)
    {
        $this->userId = $userId;

        return $this;
    }

    /**
     * Get userId
     *
     * @return integer
     */
    public function getUserId()
    {
        return $this->userId;
    }

    /**
     * Set cityId
     *
     * @param integer $cityId
     * @return UserCity
     */
    public function setCityId($cityId)
    {
        $this->cityId = $cityId;

        return $this;
    }

    /**
     * Get cityId
     *
     * @return integer
     */
    public function getCityId()
    {
        return $this->cityId;
    }
}